### ISSUE TITLE
Defunctness causes no pubs to be attempted

### ISSUE THREAD

**Issue by staltz** [staltz/ssb-conn#15]
See discussion at https://github.com/ssbc/patchwork/pull/1242

Apparently I did a big mistake with booleans:

https://github.com/staltz/ssb-conn/blob/5758e5b5fa143273d2ed2fcb7ae87de27fe43314/src/conn-scheduler.ts#L50-L56

:scream: :scream: :scream:

**Comment by staltz** [comment]
cc @christianbundy @cinnamon-bun

**Comment by christianbundy** [comment]
Thanks for finding and fixing this so quickly! :heart:

**Comment by staltz** [comment]
Hot fixed in 0.16.2.

Should probably bring back defunctness in the future, but *very carefully*. With code reviews, tests, and recovery from defunctness (see #14).
