### ISSUE TITLE
Eliminate "zii" dependency

### ISSUE THREAD

**Issue by KyleMaas** [staltz/ssb-conn#26]
Having zii pulled in makes it so that IPFS can't be combined into the same project as ssb-conn.  Reported upstream here:

https://github.com/multiformats/js-multibase/issues/80

...but I'm not sure they can fix this well without breaking their API, so it would be better if zii could be eliminated from this project.  It's too wide-reaching, and I could see it causing other odd corner cases in other places in the future.

**Comment by KyleMaas** [comment]
By the way, the reason for trying to use IPFS is so that I can do this:

https://github.com/arj03/ssb-browser-demo/issues/198

**Comment by staltz** [comment]
Yeah I'm inclined to replace zii with something else

**Comment by KyleMaas** [comment]
Cool.  It does look like it simplifies things and keeps code short.  It's just that, unfortunately, it has side effects.

**Comment by KyleMaas** [comment]
Solved with https://github.com/staltz/ssb-conn/commit/ec2a2661f534fb6b87628d0ccd6204270a611af3

**Comment by staltz** [comment]
Version 2.0.2 should solve this
